POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin123&"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "trayan",
  "password": "Trayan123&"
}

### GET All Users
GET http://localhost:8080/api/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjY5NDIwNiwiaWF0IjoxNjQyNjkwNjA2fQ.RinFtWPKF5AfOxxdmci4DZhBEnRgME8pVgfF18Yp9XNLDYQFgBZX3ft6UZ-oMXyFstCDamuMpAOIk_CQp-5Gdw

###
GET http://localhost:8080/api/users/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjY4NDkwOSwiaWF0IjoxNjQyNjgxMzA5fQ.Kl0Cm1pGk_9_lbJmHITc3SHvO3R67Q4NiAektvKTjDMwrDuZaIcRZu_aGnsG69GIZjUnWxKYBZQN3ucKE1WGFw

###

POST http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjY4NDkwOSwiaWF0IjoxNjQyNjgxMzA5fQ.Kl0Cm1pGk_9_lbJmHITc3SHvO3R67Q4NiAektvKTjDMwrDuZaIcRZu_aGnsG69GIZjUnWxKYBZQN3ucKE1WGFw

{
  "firstName": "Trayan",
  "lastName": "Iliev",
  "username": "trayan",
  "password": "Trayan123&",
  "roles": ["READER", "AUTHOR", "ADMIN"]
}

###

POST http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjY4NDkwOSwiaWF0IjoxNjQyNjgxMzA5fQ.Kl0Cm1pGk_9_lbJmHITc3SHvO3R67Q4NiAektvKTjDMwrDuZaIcRZu_aGnsG69GIZjUnWxKYBZQN3ucKE1WGFw

{
  "firstName": "Georgi",
  "lastName": "Petrov",
  "username": "george",
  "password": "George123&",
  "roles": ["READER", "AUTHOR"]
}

###
PUT http://localhost:8080/api/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjY5NDIwNiwiaWF0IjoxNjQyNjkwNjA2fQ.RinFtWPKF5AfOxxdmci4DZhBEnRgME8pVgfF18Yp9XNLDYQFgBZX3ft6UZ-oMXyFstCDamuMpAOIk_CQp-5Gdw

{
  "id": 3,
  "firstName": "Georgi",
  "lastName": "Hristov Petrov",
  "username": "george",
  "roles": [
    "READER",
    "ADMIN"
  ]
}
###

DELETE http://localhost:8080/api/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0cmF5YW4iLCJleHAiOjE2NDI2ODYwMTcsImlhdCI6MTY0MjY4MjQxN30.CF17YRb6emurTcucGQ1Dw7zWBGiJXIpH1btSkGcXwc6DOXw96VM2AS3KVxDlL1f3IlbX1cUPzdPZI2t5XkqDGQ

